"""Controls side-by-side: UC vs SCZ vs Height at broad tier (Garrido).

Track [3] interpretation gate. The controls runs (SCZ negative control,
Yengo height positive-control-calibration) executed on Garrido in this
batch, but the per-cell-type ranking was never shown next to the UC
ranking. "Runs executed" is not "validation passed" — that comparison is
the single result that decides whether UC's APC-up + T-cell-bottom
pattern is UC-specific signal or methods baseline cell-type preference.

This script pulls the three broad-tier scoring outputs (scDRS + seismic)
and emits a per-cell-type side-by-side ranking, plus a short
interpretation report flagging any cell type that ranks similarly across
UC and a control (methods-baseline crosstalk).

Inputs:
  results/scdrs/garrido_delange_seed42/UC.scdrs_group.cell_type_broad
  results/scdrs/garrido_scz/SCZ.scdrs_group.cell_type_broad
  results/scdrs/garrido_height/HEIGHT.scdrs_group.cell_type_broad
  results/seismic/garrido_delange_broad.tsv
  results/seismic/garrido_scz_broad.tsv
  results/seismic/garrido_height_broad.tsv

Outputs:
  results/concordance/controls_sidebyside_broad.csv
  results/concordance/controls_sidebyside_broad.md   (human-readable)
  results/concordance/controls_sidebyside_broad.json (machine-readable
    Spearman ρ matrix between the three GWAS within each method)

Read these BEFORE treating the APC-up / T-cell-bottom UC finding as a
biological result. If UC's ranking correlates as strongly with Height as
with itself across atlases, the bulk-T-cell-bottom finding is the
method's polygenic baseline, not UC biology.

Usage:
  py.exe code/06_concordance/controls_sidebyside_broad.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from scipy.stats import spearmanr

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parents[1]


def _load_scdrs(path: Path, gwas: str) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t")
    return df.rename(columns={
        "group": "cell_type",
        "assoc_mcz": f"{gwas}_scdrs_z",
        "assoc_mcp": f"{gwas}_scdrs_p",
    })[["cell_type", f"{gwas}_scdrs_z", f"{gwas}_scdrs_p"]]


def _load_seismic(path: Path, gwas: str) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t")
    return df.rename(columns={
        "score":  f"{gwas}_seismic_z",
        "pvalue": f"{gwas}_seismic_p",
    })[["cell_type", f"{gwas}_seismic_z", f"{gwas}_seismic_p"]]


def main() -> None:
    scdrs_dir   = _REPO / "results/scdrs"
    seismic_dir = _REPO / "results/seismic"
    out_dir     = _REPO / "results/concordance"
    out_dir.mkdir(parents=True, exist_ok=True)

    uc_scdrs     = _load_scdrs(scdrs_dir / "garrido_delange_seed42/UC.scdrs_group.cell_type_broad", "UC")
    scz_scdrs    = _load_scdrs(scdrs_dir / "garrido_scz/SCZ.scdrs_group.cell_type_broad", "SCZ")
    height_scdrs = _load_scdrs(scdrs_dir / "garrido_height/HEIGHT.scdrs_group.cell_type_broad", "HEIGHT")

    uc_seismic     = _load_seismic(seismic_dir / "garrido_delange_broad.tsv", "UC")
    scz_seismic    = _load_seismic(seismic_dir / "garrido_scz_broad.tsv", "SCZ")
    height_seismic = _load_seismic(seismic_dir / "garrido_height_broad.tsv", "HEIGHT")

    df = (
        uc_scdrs
        .merge(scz_scdrs,    on="cell_type")
        .merge(height_scdrs, on="cell_type")
        .merge(uc_seismic,     on="cell_type")
        .merge(scz_seismic,    on="cell_type")
        .merge(height_seismic, on="cell_type")
    )

    for gwas in ("UC", "SCZ", "HEIGHT"):
        for method in ("scdrs", "seismic"):
            df[f"{gwas}_{method}_rank"] = df[f"{gwas}_{method}_z"].rank(ascending=False, method="min").astype(int)

    df = df.sort_values("UC_scdrs_rank").reset_index(drop=True)
    df.to_csv(out_dir / "controls_sidebyside_broad.csv", index=False)

    rho = {}
    for method in ("scdrs", "seismic"):
        rho[method] = {}
        for a, b in [("UC", "SCZ"), ("UC", "HEIGHT"), ("SCZ", "HEIGHT")]:
            r, p = spearmanr(df[f"{a}_{method}_z"], df[f"{b}_{method}_z"])
            rho[method][f"{a}_vs_{b}"] = {"spearman_rho": float(r), "p": float(p)}
    (out_dir / "controls_sidebyside_broad.json").write_text(json.dumps(rho, indent=2))

    md_lines: list[str] = []
    md_lines.append("# Controls side-by-side — Garrido broad tier")
    md_lines.append("")
    md_lines.append("Generated by `code/06_concordance/controls_sidebyside_broad.py`.")
    md_lines.append("")
    md_lines.append("**Purpose**: gates the interpretation of the UC APC-up / T-cell-bottom")
    md_lines.append("pattern. If the same pattern appears under the SCZ negative control or")
    md_lines.append("the Yengo height positive-control-calibration, it's methods baseline,")
    md_lines.append("not UC-specific signal.")
    md_lines.append("")
    md_lines.append("## scDRS — per cell type, z-score (assoc_mcz) and rank")
    md_lines.append("")
    md_lines.append("| cell_type | UC z | UC rank | SCZ z | SCZ rank | Height z | Height rank |")
    md_lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for _, r in df.iterrows():
        md_lines.append(
            f"| {r['cell_type']} | {r['UC_scdrs_z']:+.2f} | {r['UC_scdrs_rank']} "
            f"| {r['SCZ_scdrs_z']:+.2f} | {r['SCZ_scdrs_rank']} "
            f"| {r['HEIGHT_scdrs_z']:+.2f} | {r['HEIGHT_scdrs_rank']} |"
        )
    md_lines.append("")
    md_lines.append("## seismic — per cell type, score (effect size) and rank")
    md_lines.append("")
    md_lines.append("| cell_type | UC z | UC rank | SCZ z | SCZ rank | Height z | Height rank |")
    md_lines.append("|---|---:|---:|---:|---:|---:|---:|")
    for _, r in df.sort_values("UC_seismic_rank").iterrows():
        md_lines.append(
            f"| {r['cell_type']} | {r['UC_seismic_z']:+.2f} | {r['UC_seismic_rank']} "
            f"| {r['SCZ_seismic_z']:+.2f} | {r['SCZ_seismic_rank']} "
            f"| {r['HEIGHT_seismic_z']:+.2f} | {r['HEIGHT_seismic_rank']} |"
        )
    md_lines.append("")
    md_lines.append("## Cross-GWAS Spearman ρ within each method")
    md_lines.append("")
    md_lines.append("ρ near 0 = UC ranking is GWAS-specific (good).")
    md_lines.append("ρ near 1 = UC ranking mirrors the control = methods cell-type baseline.")
    md_lines.append("")
    md_lines.append("| method | UC vs SCZ | UC vs Height | SCZ vs Height |")
    md_lines.append("|---|---:|---:|---:|")
    for method in ("scdrs", "seismic"):
        md_lines.append(
            f"| {method} "
            f"| {rho[method]['UC_vs_SCZ']['spearman_rho']:+.3f} "
            f"| {rho[method]['UC_vs_HEIGHT']['spearman_rho']:+.3f} "
            f"| {rho[method]['SCZ_vs_HEIGHT']['spearman_rho']:+.3f} |"
        )
    md_lines.append("")
    md_lines.append("## Per-cell-type crosstalk flags")
    md_lines.append("")
    md_lines.append("A flag fires for a cell type when its UC rank and a control's rank")
    md_lines.append("are both in the top 3 or both in the bottom 3 within a method.")
    md_lines.append("")
    flags: list[str] = []
    n = len(df)
    top_k, bot_k = 3, 3
    for method in ("scdrs", "seismic"):
        for control in ("SCZ", "HEIGHT"):
            for _, r in df.iterrows():
                uc_rank = r[f"UC_{method}_rank"]
                cr_rank = r[f"{control}_{method}_rank"]
                if uc_rank <= top_k and cr_rank <= top_k:
                    flags.append(
                        f"- **{method}** · top-{top_k} crosstalk: `{r['cell_type']}` "
                        f"is rank {uc_rank} for UC AND rank {cr_rank} for {control}"
                    )
                if uc_rank > n - bot_k and cr_rank > n - bot_k:
                    flags.append(
                        f"- **{method}** · bottom-{bot_k} crosstalk: `{r['cell_type']}` "
                        f"is rank {uc_rank} for UC AND rank {cr_rank} for {control}"
                    )
    if flags:
        md_lines.extend(flags)
    else:
        md_lines.append("- (no crosstalk in either method's top-3 or bottom-3.)")
    md_lines.append("")
    md_lines.append("## How to read this")
    md_lines.append("")
    md_lines.append("- **APC-up signal** (colonocyte / epithelial progenitor near top): if it")
    md_lines.append("  is UC-only (i.e. not in SCZ top-3 and not in Height top-3), the UC")
    md_lines.append("  finding is GWAS-specific signal.")
    md_lines.append("- **T-cell-bottom signal**: if T cell is also bottom-ranked for the")
    md_lines.append("  Height calibration, the bottom rank is the method's baseline polygenic")
    md_lines.append("  non-prioritization of T cells in this gut atlas (Height is non-immune-")
    md_lines.append("  specific by design; T-cell-bottom there means the method puts T cells")
    md_lines.append("  bottom for any well-powered polygenic non-immune trait). UC's T-cell-")
    md_lines.append("  bottom then cannot be claimed as UC biology from this atlas alone.")
    md_lines.append("- **scDRS vs seismic divergence**: if the two methods disagree on whether")
    md_lines.append("  T-cell-bottom is UC-specific, the divergence itself is the next test —")
    md_lines.append("  cross-method should be reported, not averaged away.")
    md_lines.append("")

    (out_dir / "controls_sidebyside_broad.md").write_text("\n".join(md_lines), encoding="utf-8")

    print(f"Wrote: {out_dir / 'controls_sidebyside_broad.csv'}")
    print(f"Wrote: {out_dir / 'controls_sidebyside_broad.md'}")
    print(f"Wrote: {out_dir / 'controls_sidebyside_broad.json'}")


if __name__ == "__main__":
    main()
